#afterbuild #docker-compose.yml #version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mex_database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mex_database"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  data_ingestion:
    build:
      context: ./data_ingestion
    image: bhargavdeekshithvasu1997/mars_express_orbiter:data_ingestion
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./data:/app/data
      - flags_volume:/flags

  preprocessing:
    build:
      context: ./preprocessing
    image: bhargavdeekshithvasu1997/mars_express_orbiter:preprocessing
    depends_on:
      data_ingestion:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - flags_volume:/flags

  model_training:
    build:
      context: ./model_training
    image: bhargavdeekshithvasu1997/mars_express_orbiter:model_training
    depends_on:
      preprocessing:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./models:/models
      - flags_volume:/flags

  model_testing:
    build:
      context: ./model_testing
    image: bhargavdeekshithvasu1997/mars_express_orbiter:model_testing
    depends_on:
      model_training:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./models:/models
      - ./results:/results
      - flags_volume:/flags

  data_visualization:
    image: bhargavdeekshithvasu1997/mars_express_orbiter:data_visualization
    depends_on:
      model_testing:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mex_database
      DB_USER: admin
      DB_PASS: 1234
    volumes:
      - ./models:/models
      - ./results:/results
      - flags_volume:/flags
    ports:
      - "8501:8501"

volumes:
  db_data:
  flags_volume:
